export interface ParkingSpace {
  number: string;
  size: "大" | "小" | "身障";
  allocation: "重" | "A" | "B" | "C" | "店" | "保留";
  isAvailable: boolean;
}

export interface LotteryRules {
  noRestriction: boolean;
  onlyStore: boolean;
  onlyDisabled: boolean;
  onlyMotorcycle: boolean;
  largePriority: boolean;
  excludeStore: boolean;
  excludeDisabled: boolean;
  excludeMotorcycle: boolean;
  areaRestriction: boolean;
}

export interface LotteryFormData {
  selectedResidents: string[];
  bulkInput: string; // 新增
  rules: LotteryRules;
}

export interface Resident {
  id: string;
  unitNumber: string;
  area: "S" | "A" | "B" | "C";
}

export const residents: Resident[] = [
  { id: "S01F01", unitNumber: "S01F01", area: "S" },
  { id: "S02F01", unitNumber: "S02F01", area: "S" },
  { id: "S03F01", unitNumber: "S03F01", area: "S" },
  { id: "S05F01", unitNumber: "S05F01", area: "S" },
  { id: "S06F01", unitNumber: "S06F01", area: "S" },
  { id: "S07F01", unitNumber: "S07F01", area: "S" },
  { id: "S08F01", unitNumber: "S08F01", area: "S" },
  { id: "S09F01", unitNumber: "S09F01", area: "S" },
  { id: "S10F01", unitNumber: "S10F01", area: "S" },
  { id: "S11F01", unitNumber: "S11F01", area: "S" },
  { id: "S12F01", unitNumber: "S12F01", area: "S" },
  { id: "S13F01", unitNumber: "S13F01", area: "S" },
  { id: "S15F01", unitNumber: "S15F01", area: "S" },
  { id: "S16F01", unitNumber: "S16F01", area: "S" },
  { id: "S17F01", unitNumber: "S17F01", area: "S" },
  { id: "S18F01", unitNumber: "S18F01", area: "S" },
  { id: "S19F01", unitNumber: "S19F01", area: "S" },
  { id: "S20F01", unitNumber: "S20F01", area: "S" },
  { id: "S21F01", unitNumber: "S21F01", area: "S" },
  { id: "S22F01", unitNumber: "S22F01", area: "S" },
  // A區住戶 (修改這裡)
  { id: "A01F04", unitNumber: "A01F04", area: "A" },
  { id: "A01F05", unitNumber: "A01F05", area: "A" },
  { id: "A01F06", unitNumber: "A01F06", area: "A" },
  { id: "A01F07", unitNumber: "A01F07", area: "A" },
  { id: "A01F08", unitNumber: "A01F08", area: "A" },
  { id: "A01F09", unitNumber: "A01F09", area: "A" },
  { id: "A01F10", unitNumber: "A01F10", area: "A" },
  { id: "A01F11", unitNumber: "A01F11", area: "A" },
  { id: "A01F12", unitNumber: "A01F12", area: "A" },
  { id: "A01F13", unitNumber: "A01F13", area: "A" },
  { id: "A01F14", unitNumber: "A01F14", area: "A" },
  { id: "A01F15", unitNumber: "A01F15", area: "A" },
  { id: "A01F16", unitNumber: "A01F16", area: "A" },
  { id: "A01F17", unitNumber: "A01F17", area: "A" },
  { id: "A01F18", unitNumber: "A01F18", area: "A" },
  { id: "A01F19", unitNumber: "A01F19", area: "A" },
  { id: "A01F20", unitNumber: "A01F20", area: "A" },
  { id: "A01F21", unitNumber: "A01F21", area: "A" },
  { id: "A01F22", unitNumber: "A01F22", area: "A" },
  { id: "A01F23", unitNumber: "A01F23", area: "A" },
  { id: "A02F03", unitNumber: "A02F03", area: "A" },
  { id: "A02F04", unitNumber: "A02F04", area: "A" },
  { id: "A02F05", unitNumber: "A02F05", area: "A" },
  { id: "A02F06", unitNumber: "A02F06", area: "A" },
  { id: "A02F07", unitNumber: "A02F07", area: "A" },
  { id: "A02F08", unitNumber: "A02F08", area: "A" },
  { id: "A02F09", unitNumber: "A02F09", area: "A" },
  { id: "A02F10", unitNumber: "A02F10", area: "A" },
  { id: "A02F11", unitNumber: "A02F11", area: "A" },
  { id: "A02F12", unitNumber: "A02F12", area: "A" },
  { id: "A02F13", unitNumber: "A02F13", area: "A" },
  { id: "A02F15", unitNumber: "A02F15", area: "A" },
  { id: "A02F16", unitNumber: "A02F16", area: "A" },
  { id: "A02F17", unitNumber: "A02F17", area: "A" },
  { id: "A02F18", unitNumber: "A02F18", area: "A" },
  { id: "A02F19", unitNumber: "A02F19", area: "A" },
  { id: "A02F20", unitNumber: "A02F20", area: "A" },
  { id: "A02F21", unitNumber: "A02F21", area: "A" },
  { id: "A02F22", unitNumber: "A02F22", area: "A" },
  { id: "A02F23", unitNumber: "A02F23", area: "A" },
  { id: "A03F03", unitNumber: "A03F03", area: "A" },
  { id: "A03F04", unitNumber: "A03F04", area: "A" },
  { id: "A03F05", unitNumber: "A03F05", area: "A" },
  { id: "A03F06", unitNumber: "A03F06", area: "A" },
  { id: "A03F07", unitNumber: "A03F07", area: "A" },
  { id: "A03F08", unitNumber: "A03F08", area: "A" },
  { id: "A03F09", unitNumber: "A03F09", area: "A" },
  { id: "A03F10", unitNumber: "A03F10", area: "A" },
  { id: "A03F11", unitNumber: "A03F11", area: "A" },
  { id: "A03F12", unitNumber: "A03F12", area: "A" },
  { id: "A03F13", unitNumber: "A03F13", area: "A" },
  { id: "A03F14", unitNumber: "A03F14", area: "A" },
  { id: "A03F15", unitNumber: "A03F15", area: "A" },
  { id: "A03F16", unitNumber: "A03F16", area: "A" },
  { id: "A03F17", unitNumber: "A03F17", area: "A" },
  { id: "A03F18", unitNumber: "A03F18", area: "A" },
  { id: "A03F19", unitNumber: "A03F19", area: "A" },
  { id: "A03F20", unitNumber: "A03F20", area: "A" },
  { id: "A03F21", unitNumber: "A03F21", area: "A" },
  { id: "A03F22", unitNumber: "A03F22", area: "A" },
  { id: "A03F23", unitNumber: "A03F23", area: "A" },
  { id: "A05F03", unitNumber: "A05F03", area: "A" },
  { id: "A05F04", unitNumber: "A05F04", area: "A" },
  { id: "A05F05", unitNumber: "A05F05", area: "A" },
  { id: "A05F06", unitNumber: "A05F06", area: "A" },
  { id: "A05F07", unitNumber: "A05F07", area: "A" },
  { id: "A05F08", unitNumber: "A05F08", area: "A" },
  { id: "A05F09", unitNumber: "A05F09", area: "A" },
  { id: "A05F10", unitNumber: "A05F10", area: "A" },
  { id: "A05F11", unitNumber: "A05F11", area: "A" },
  { id: "A05F12", unitNumber: "A05F12", area: "A" },
  { id: "A05F13", unitNumber: "A05F13", area: "A" },
  { id: "A05F14", unitNumber: "A05F14", area: "A" },
  { id: "A05F15", unitNumber: "A05F15", area: "A" },
  { id: "A05F16", unitNumber: "A05F16", area: "A" },
  { id: "A05F17", unitNumber: "A05F17", area: "A" },
  { id: "A05F18", unitNumber: "A05F18", area: "A" },
  { id: "A05F19", unitNumber: "A05F19", area: "A" },
  { id: "A05F20", unitNumber: "A05F20", area: "A" },
  { id: "A05F21", unitNumber: "A05F21", area: "A" },
  { id: "A05F22", unitNumber: "A05F22", area: "A" },
  { id: "A05F23", unitNumber: "A05F23", area: "A" },
  { id: "A06F03", unitNumber: "A06F03", area: "A" },
  { id: "A06F04", unitNumber: "A06F04", area: "A" },
  { id: "A06F05", unitNumber: "A06F05", area: "A" },
  { id: "A06F06", unitNumber: "A06F06", area: "A" },
  { id: "A06F07", unitNumber: "A06F07", area: "A" },
  { id: "A06F08", unitNumber: "A06F08", area: "A" },
  { id: "A06F09", unitNumber: "A06F09", area: "A" },
  { id: "A06F10", unitNumber: "A06F10", area: "A" },
  { id: "A06F11", unitNumber: "A06F11", area: "A" },
  { id: "A06F12", unitNumber: "A06F12", area: "A" },
  { id: "A06F13", unitNumber: "A06F13", area: "A" },
  { id: "A06F14", unitNumber: "A06F14", area: "A" },
  { id: "A06F15", unitNumber: "A06F15", area: "A" },
  { id: "A06F16", unitNumber: "A06F16", area: "A" },
  { id: "A06F17", unitNumber: "A06F17", area: "A" },
  { id: "A06F18", unitNumber: "A06F18", area: "A" },
  { id: "A06F19", unitNumber: "A06F19", area: "A" },
  { id: "A06F20", unitNumber: "A06F20", area: "A" },
  { id: "A06F21", unitNumber: "A06F21", area: "A" },
  { id: "A06F22", unitNumber: "A06F22", area: "A" },
  { id: "A06F23", unitNumber: "A06F23", area: "A" },
  { id: "A07F03", unitNumber: "A07F03", area: "A" },
  { id: "A07F04", unitNumber: "A07F04", area: "A" },
  { id: "A07F05", unitNumber: "A07F05", area: "A" },
  { id: "A07F06", unitNumber: "A07F06", area: "A" },
  { id: "A07F07", unitNumber: "A07F07", area: "A" },
  { id: "A07F08", unitNumber: "A07F08", area: "A" },
  { id: "A07F09", unitNumber: "A07F09", area: "A" },
  { id: "A07F10", unitNumber: "A07F10", area: "A" },
  { id: "A07F11", unitNumber: "A07F11", area: "A" },
  { id: "A07F12", unitNumber: "A07F12", area: "A" },
  { id: "A07F13", unitNumber: "A07F13", area: "A" },
  { id: "A07F14", unitNumber: "A07F14", area: "A" },
  { id: "A07F15", unitNumber: "A07F15", area: "A" },
  { id: "A07F16", unitNumber: "A07F16", area: "A" },
  { id: "A07F17", unitNumber: "A07F17", area: "A" },
  { id: "A07F18", unitNumber: "A07F18", area: "A" },
  { id: "A07F19", unitNumber: "A07F19", area: "A" },
  { id: "A07F20", unitNumber: "A07F20", area: "A" },
  { id: "A07F21", unitNumber: "A07F21", area: "A" },
  { id: "A07F22", unitNumber: "A07F22", area: "A" },
  { id: "A07F23", unitNumber: "A07F23", area: "A" },
  { id: "A08F04", unitNumber: "A08F04", area: "A" },
  { id: "A08F05", unitNumber: "A08F05", area: "A" },
  { id: "A08F06", unitNumber: "A08F06", area: "A" },
  { id: "A08F07", unitNumber: "A08F07", area: "A" },
  { id: "A08F08", unitNumber: "A08F08", area: "A" },
  { id: "A08F09", unitNumber: "A08F09", area: "A" },
  { id: "A08F10", unitNumber: "A08F10", area: "A" },
  { id: "A08F11", unitNumber: "A08F11", area: "A" },
  { id: "A08F12", unitNumber: "A08F12", area: "A" },
  { id: "A08F13", unitNumber: "A08F13", area: "A" },
  { id: "A08F14", unitNumber: "A08F14", area: "A" },
  { id: "A08F15", unitNumber: "A08F15", area: "A" },
  { id: "A08F16", unitNumber: "A08F16", area: "A" },
  { id: "A08F17", unitNumber: "A08F17", area: "A" },
  { id: "A08F18", unitNumber: "A08F18", area: "A" },
  { id: "A08F19", unitNumber: "A08F19", area: "A" },
  { id: "A08F20", unitNumber: "A08F20", area: "A" },
  { id: "A08F21", unitNumber: "A08F21", area: "A" },
  { id: "A08F22", unitNumber: "A08F22", area: "A" },
  { id: "A08F23", unitNumber: "A08F23", area: "A" },
  // B區住戶
  { id: "B01F04", unitNumber: "B01F04", area: "B" },
  { id: "B01F05", unitNumber: "B01F05", area: "B" },
  { id: "B01F06", unitNumber: "B01F06", area: "B" },
  { id: "B01F07", unitNumber: "B01F07", area: "B" },
  { id: "B01F08", unitNumber: "B01F08", area: "B" },
  { id: "B01F09", unitNumber: "B01F09", area: "B" },
  { id: "B01F10", unitNumber: "B01F10", area: "B" },
  { id: "B01F11", unitNumber: "B01F11", area: "B" },
  { id: "B01F12", unitNumber: "B01F12", area: "B" },
  { id: "B01F13", unitNumber: "B01F13", area: "B" },
  { id: "B01F14", unitNumber: "B01F14", area: "B" },
  { id: "B01F15", unitNumber: "B01F15", area: "B" },
  { id: "B01F16", unitNumber: "B01F16", area: "B" },
  { id: "B01F17", unitNumber: "B01F17", area: "B" },
  { id: "B01F18", unitNumber: "B01F18", area: "B" },
  { id: "B01F19", unitNumber: "B01F19", area: "B" },
  { id: "B01F20", unitNumber: "B01F20", area: "B" },
  { id: "B01F21", unitNumber: "B01F21", area: "B" },
  { id: "B01F22", unitNumber: "B01F22", area: "B" },
  { id: "B01F23", unitNumber: "B01F23", area: "B" },
  { id: "B02F04", unitNumber: "B02F04", area: "B" },
  { id: "B02F05", unitNumber: "B02F05", area: "B" },
  { id: "B02F06", unitNumber: "B02F06", area: "B" },
  { id: "B02F07", unitNumber: "B02F07", area: "B" },
  { id: "B02F08", unitNumber: "B02F08", area: "B" },
  { id: "B02F09", unitNumber: "B02F09", area: "B" },
  { id: "B02F10", unitNumber: "B02F10", area: "B" },
  { id: "B02F11", unitNumber: "B02F11", area: "B" },
  { id: "B02F12", unitNumber: "B02F12", area: "B" },
  { id: "B02F13", unitNumber: "B02F13", area: "B" },
  { id: "B02F14", unitNumber: "B02F14", area: "B" },
  { id: "B02F15", unitNumber: "B02F15", area: "B" },
  { id: "B02F16", unitNumber: "B02F16", area: "B" },
  { id: "B02F17", unitNumber: "B02F17", area: "B" },
  { id: "B02F18", unitNumber: "B02F18", area: "B" },
  { id: "B02F19", unitNumber: "B02F19", area: "B" },
  { id: "B02F20", unitNumber: "B02F20", area: "B" },
  { id: "B02F21", unitNumber: "B02F21", area: "B" },
  { id: "B02F22", unitNumber: "B02F22", area: "B" },
  { id: "B02F23", unitNumber: "B02F23", area: "B" },
  { id: "B03F04", unitNumber: "B03F04", area: "B" },
  { id: "B03F05", unitNumber: "B03F05", area: "B" },
  { id: "B03F06", unitNumber: "B03F06", area: "B" },
  { id: "B03F07", unitNumber: "B03F07", area: "B" },
  { id: "B03F08", unitNumber: "B03F08", area: "B" },
  { id: "B03F09", unitNumber: "B03F09", area: "B" },
  { id: "B03F10", unitNumber: "B03F10", area: "B" },
  { id: "B03F11", unitNumber: "B03F11", area: "B" },
  { id: "B03F12", unitNumber: "B03F12", area: "B" },
  { id: "B03F13", unitNumber: "B03F13", area: "B" },
  { id: "B03F14", unitNumber: "B03F14", area: "B" },
  { id: "B03F15", unitNumber: "B03F15", area: "B" },
  { id: "B03F16", unitNumber: "B03F16", area: "B" },
  { id: "B03F17", unitNumber: "B03F17", area: "B" },
  { id: "B03F18", unitNumber: "B03F18", area: "B" },
  { id: "B03F19", unitNumber: "B03F19", area: "B" },
  { id: "B03F20", unitNumber: "B03F20", area: "B" },
  { id: "B03F21", unitNumber: "B03F21", area: "B" },
  { id: "B03F22", unitNumber: "B03F22", area: "B" },
  { id: "B03F23", unitNumber: "B03F23", area: "B" },
  { id: "B05F04", unitNumber: "B05F04", area: "B" },
  { id: "B05F05", unitNumber: "B05F05", area: "B" },
  { id: "B05F06", unitNumber: "B05F06", area: "B" },
  { id: "B05F07", unitNumber: "B05F07", area: "B" },
  { id: "B05F08", unitNumber: "B05F08", area: "B" },
  { id: "B05F09", unitNumber: "B05F09", area: "B" },
  { id: "B05F10", unitNumber: "B05F10", area: "B" },
  { id: "B05F11", unitNumber: "B05F11", area: "B" },
  { id: "B05F12", unitNumber: "B05F12", area: "B" },
  { id: "B05F13", unitNumber: "B05F13", area: "B" },
  { id: "B05F14", unitNumber: "B05F14", area: "B" },
  { id: "B05F15", unitNumber: "B05F15", area: "B" },
  { id: "B05F16", unitNumber: "B05F16", area: "B" },
  { id: "B05F17", unitNumber: "B05F17", area: "B" },
  { id: "B05F18", unitNumber: "B05F18", area: "B" },
  { id: "B05F19", unitNumber: "B05F19", area: "B" },
  { id: "B05F20", unitNumber: "B05F20", area: "B" },
  { id: "B05F21", unitNumber: "B05F21", area: "B" },
  { id: "B05F22", unitNumber: "B05F22", area: "B" },
  { id: "B05F23", unitNumber: "B05F23", area: "B" },
  { id: "B06F04", unitNumber: "B06F04", area: "B" },
  { id: "B06F05", unitNumber: "B06F05", area: "B" },
  { id: "B06F06", unitNumber: "B06F06", area: "B" },
  { id: "B06F07", unitNumber: "B06F07", area: "B" },
  { id: "B06F08", unitNumber: "B06F08", area: "B" },
  { id: "B06F09", unitNumber: "B06F09", area: "B" },
  { id: "B06F10", unitNumber: "B06F10", area: "B" },
  { id: "B06F11", unitNumber: "B06F11", area: "B" },
  { id: "B06F12", unitNumber: "B06F12", area: "B" },
  { id: "B06F13", unitNumber: "B06F13", area: "B" },
  { id: "B06F14", unitNumber: "B06F14", area: "B" },
  { id: "B06F15", unitNumber: "B06F15", area: "B" },
  { id: "B06F16", unitNumber: "B06F16", area: "B" },
  { id: "B06F17", unitNumber: "B06F17", area: "B" },
  { id: "B06F18", unitNumber: "B06F18", area: "B" },
  { id: "B06F19", unitNumber: "B06F19", area: "B" },
  { id: "B06F20", unitNumber: "B06F20", area: "B" },
  { id: "B06F21", unitNumber: "B06F21", area: "B" },
  { id: "B06F22", unitNumber: "B06F22", area: "B" },
  { id: "B06F23", unitNumber: "B06F23", area: "B" },
  { id: "B07F04", unitNumber: "B07F04", area: "B" },
  { id: "B07F05", unitNumber: "B07F05", area: "B" },
  { id: "B07F06", unitNumber: "B07F06", area: "B" },
  { id: "B07F07", unitNumber: "B07F07", area: "B" },
  { id: "B07F08", unitNumber: "B07F08", area: "B" },
  { id: "B07F09", unitNumber: "B07F09", area: "B" },
  { id: "B07F10", unitNumber: "B07F10", area: "B" },
  { id: "B07F11", unitNumber: "B07F11", area: "B" },
  { id: "B07F12", unitNumber: "B07F12", area: "B" },
  { id: "B07F13", unitNumber: "B07F13", area: "B" },
  { id: "B07F14", unitNumber: "B07F14", area: "B" },
  { id: "B07F15", unitNumber: "B07F15", area: "B" },
  { id: "B07F16", unitNumber: "B07F16", area: "B" },
  { id: "B07F17", unitNumber: "B07F17", area: "B" },
  { id: "B07F18", unitNumber: "B07F18", area: "B" },
  { id: "B07F19", unitNumber: "B07F19", area: "B" },
  { id: "B07F20", unitNumber: "B07F20", area: "B" },
  { id: "B07F21", unitNumber: "B07F21", area: "B" },
  { id: "B07F22", unitNumber: "B07F22", area: "B" },
  { id: "B07F23", unitNumber: "B07F23", area: "B" },
  { id: "B08F04", unitNumber: "B08F04", area: "B" },
  { id: "B08F05", unitNumber: "B08F05", area: "B" },
  { id: "B08F06", unitNumber: "B08F06", area: "B" },
  { id: "B08F07", unitNumber: "B08F07", area: "B" },
  { id: "B08F08", unitNumber: "B08F08", area: "B" },
  { id: "B08F09", unitNumber: "B08F09", area: "B" },
  { id: "B08F10", unitNumber: "B08F10", area: "B" },
  { id: "B08F11", unitNumber: "B08F11", area: "B" },
  { id: "B08F12", unitNumber: "B08F12", area: "B" },
  { id: "B08F13", unitNumber: "B08F13", area: "B" },
  { id: "B08F14", unitNumber: "B08F14", area: "B" },
  { id: "B08F15", unitNumber: "B08F15", area: "B" },
  { id: "B08F16", unitNumber: "B08F16", area: "B" },
  { id: "B08F17", unitNumber: "B08F17", area: "B" },
  { id: "B08F18", unitNumber: "B08F18", area: "B" },
  { id: "B08F19", unitNumber: "B08F19", area: "B" },
  { id: "B08F20", unitNumber: "B08F20", area: "B" },
  { id: "B08F21", unitNumber: "B08F21", area: "B" },
  { id: "B08F22", unitNumber: "B08F22", area: "B" },
  { id: "B08F23", unitNumber: "B08F23", area: "B" },
  { id: "B09F04", unitNumber: "B09F04", area: "B" },
  { id: "B09F05", unitNumber: "B09F05", area: "B" },
  { id: "B09F06", unitNumber: "B09F06", area: "B" },
  { id: "B09F07", unitNumber: "B09F07", area: "B" },
  { id: "B09F08", unitNumber: "B09F08", area: "B" },
  { id: "B09F09", unitNumber: "B09F09", area: "B" },
  { id: "B09F10", unitNumber: "B09F10", area: "B" },
  { id: "B09F11", unitNumber: "B09F11", area: "B" },
  { id: "B09F12", unitNumber: "B09F12", area: "B" },
  { id: "B09F13", unitNumber: "B09F13", area: "B" },
  { id: "B09F14", unitNumber: "B09F14", area: "B" },
  { id: "B09F15", unitNumber: "B09F15", area: "B" },
  { id: "B09F16", unitNumber: "B09F16", area: "B" },
  { id: "B09F17", unitNumber: "B09F17", area: "B" },
  { id: "B09F18", unitNumber: "B09F18", area: "B" },
  { id: "B09F19", unitNumber: "B09F19", area: "B" },
  { id: "B09F20", unitNumber: "B09F20", area: "B" },
  { id: "B09F21", unitNumber: "B09F21", area: "B" },
  { id: "B09F22", unitNumber: "B09F22", area: "B" },
  { id: "B09F23", unitNumber: "B09F23", area: "B" },

  // C區住戶
  { id: "C01F03", unitNumber: "C01F03", area: "C" },
  { id: "C01F04", unitNumber: "C01F04", area: "C" },
  { id: "C01F05", unitNumber: "C01F05", area: "C" },
  { id: "C01F06", unitNumber: "C01F06", area: "C" },
  { id: "C01F07", unitNumber: "C01F07", area: "C" },
  { id: "C01F08", unitNumber: "C01F08", area: "C" },
  { id: "C01F09", unitNumber: "C01F09", area: "C" },
  { id: "C01F10", unitNumber: "C01F10", area: "C" },
  { id: "C01F11", unitNumber: "C01F11", area: "C" },
  { id: "C01F12", unitNumber: "C01F12", area: "C" },
  { id: "C01F13", unitNumber: "C01F13", area: "C" },
  { id: "C01F14", unitNumber: "C01F14", area: "C" },
  { id: "C01F15", unitNumber: "C01F15", area: "C" },
  { id: "C01F16", unitNumber: "C01F16", area: "C" },
  { id: "C01F17", unitNumber: "C01F17", area: "C" },
  { id: "C01F18", unitNumber: "C01F18", area: "C" },
  { id: "C01F19", unitNumber: "C01F19", area: "C" },
  { id: "C01F20", unitNumber: "C01F20", area: "C" },
  { id: "C01F21", unitNumber: "C01F21", area: "C" },
  { id: "C01F22", unitNumber: "C01F22", area: "C" },
  { id: "C01F23", unitNumber: "C01F23", area: "C" },
  { id: "C02F03", unitNumber: "C02F03", area: "C" },
  { id: "C02F04", unitNumber: "C02F04", area: "C" },
  { id: "C02F05", unitNumber: "C02F05", area: "C" },
  { id: "C02F06", unitNumber: "C02F06", area: "C" },
  { id: "C02F07", unitNumber: "C02F07", area: "C" },
  { id: "C02F08", unitNumber: "C02F08", area: "C" },
  { id: "C02F09", unitNumber: "C02F09", area: "C" },
  { id: "C02F10", unitNumber: "C02F10", area: "C" },
  { id: "C02F11", unitNumber: "C02F11", area: "C" },
  { id: "C02F12", unitNumber: "C02F12", area: "C" },
  { id: "C02F13", unitNumber: "C02F13", area: "C" },
  { id: "C02F14", unitNumber: "C02F14", area: "C" },
  { id: "C02F15", unitNumber: "C02F15", area: "C" },
  { id: "C02F16", unitNumber: "C02F16", area: "C" },
  { id: "C02F17", unitNumber: "C02F17", area: "C" },
  { id: "C02F18", unitNumber: "C02F18", area: "C" },
  { id: "C02F19", unitNumber: "C02F19", area: "C" },
  { id: "C02F20", unitNumber: "C02F20", area: "C" },
  { id: "C02F21", unitNumber: "C02F21", area: "C" },
  { id: "C02F22", unitNumber: "C02F22", area: "C" },
  { id: "C02F23", unitNumber: "C02F23", area: "C" },
  { id: "C03F04", unitNumber: "C03F04", area: "C" },
  { id: "C03F05", unitNumber: "C03F05", area: "C" },
  { id: "C03F06", unitNumber: "C03F06", area: "C" },
  { id: "C03F07", unitNumber: "C03F07", area: "C" },
  { id: "C03F08", unitNumber: "C03F08", area: "C" },
  { id: "C03F09", unitNumber: "C03F09", area: "C" },
  { id: "C03F10", unitNumber: "C03F10", area: "C" },
  { id: "C03F11", unitNumber: "C03F11", area: "C" },
  { id: "C03F12", unitNumber: "C03F12", area: "C" },
  { id: "C03F13", unitNumber: "C03F13", area: "C" },
  { id: "C03F14", unitNumber: "C03F14", area: "C" },
  { id: "C03F15", unitNumber: "C03F15", area: "C" },
  { id: "C03F16", unitNumber: "C03F16", area: "C" },
  { id: "C03F17", unitNumber: "C03F17", area: "C" },
  { id: "C03F18", unitNumber: "C03F18", area: "C" },
  { id: "C03F19", unitNumber: "C03F19", area: "C" },
  { id: "C03F20", unitNumber: "C03F20", area: "C" },
  { id: "C03F21", unitNumber: "C03F21", area: "C" },
  { id: "C03F22", unitNumber: "C03F22", area: "C" },
  { id: "C03F23", unitNumber: "C03F23", area: "C" },
  { id: "C05F04", unitNumber: "C05F04", area: "C" },
  { id: "C05F05", unitNumber: "C05F05", area: "C" },
  { id: "C05F06", unitNumber: "C05F06", area: "C" },
  { id: "C05F07", unitNumber: "C05F07", area: "C" },
  { id: "C05F08", unitNumber: "C05F08", area: "C" },
  { id: "C05F09", unitNumber: "C05F09", area: "C" },
  { id: "C05F10", unitNumber: "C05F10", area: "C" },
  { id: "C05F11", unitNumber: "C05F11", area: "C" },
  { id: "C05F12", unitNumber: "C05F12", area: "C" },
  { id: "C05F13", unitNumber: "C05F13", area: "C" },
  { id: "C05F14", unitNumber: "C05F14", area: "C" },
  { id: "C05F15", unitNumber: "C05F15", area: "C" },
  { id: "C05F16", unitNumber: "C05F16", area: "C" },
  { id: "C05F17", unitNumber: "C05F17", area: "C" },
  { id: "C05F18", unitNumber: "C05F18", area: "C" },
  { id: "C05F19", unitNumber: "C05F19", area: "C" },
  { id: "C05F20", unitNumber: "C05F20", area: "C" },
  { id: "C05F21", unitNumber: "C05F21", area: "C" },
  { id: "C05F22", unitNumber: "C05F22", area: "C" },
  { id: "C05F23", unitNumber: "C05F23", area: "C" },
  { id: "C06F03", unitNumber: "C06F03", area: "C" },
  { id: "C06F04", unitNumber: "C06F04", area: "C" },
  { id: "C06F05", unitNumber: "C06F05", area: "C" },
  { id: "C06F06", unitNumber: "C06F06", area: "C" },
  { id: "C06F07", unitNumber: "C06F07", area: "C" },
  { id: "C06F08", unitNumber: "C06F08", area: "C" },
  { id: "C06F09", unitNumber: "C06F09", area: "C" },
  { id: "C06F10", unitNumber: "C06F10", area: "C" },
  { id: "C06F11", unitNumber: "C06F11", area: "C" },
  { id: "C06F12", unitNumber: "C06F12", area: "C" },
  { id: "C06F13", unitNumber: "C06F13", area: "C" },
  { id: "C06F14", unitNumber: "C06F14", area: "C" },
  { id: "C06F15", unitNumber: "C06F15", area: "C" },
  { id: "C06F16", unitNumber: "C06F16", area: "C" },
  { id: "C06F17", unitNumber: "C06F17", area: "C" },
  { id: "C06F18", unitNumber: "C06F18", area: "C" },
  { id: "C06F19", unitNumber: "C06F19", area: "C" },
  { id: "C06F20", unitNumber: "C06F20", area: "C" },
  { id: "C06F21", unitNumber: "C06F21", area: "C" },
  { id: "C06F22", unitNumber: "C06F22", area: "C" },
  { id: "C06F23", unitNumber: "C06F23", area: "C" },
  { id: "C07F03", unitNumber: "C07F03", area: "C" },
  { id: "C07F04", unitNumber: "C07F04", area: "C" },
  { id: "C07F05", unitNumber: "C07F05", area: "C" },
  { id: "C07F06", unitNumber: "C07F06", area: "C" },
  { id: "C07F07", unitNumber: "C07F07", area: "C" },
  { id: "C07F08", unitNumber: "C07F08", area: "C" },
  { id: "C07F09", unitNumber: "C07F09", area: "C" },
  { id: "C07F10", unitNumber: "C07F10", area: "C" },
  { id: "C07F11", unitNumber: "C07F11", area: "C" },
  { id: "C07F12", unitNumber: "C07F12", area: "C" },
  { id: "C07F13", unitNumber: "C07F13", area: "C" },
  { id: "C07F14", unitNumber: "C07F14", area: "C" },
  { id: "C07F15", unitNumber: "C07F15", area: "C" },
  { id: "C07F16", unitNumber: "C07F16", area: "C" },
  { id: "C07F17", unitNumber: "C07F17", area: "C" },
  { id: "C07F18", unitNumber: "C07F18", area: "C" },
  { id: "C07F19", unitNumber: "C07F19", area: "C" },
  { id: "C07F20", unitNumber: "C07F20", area: "C" },
  { id: "C07F21", unitNumber: "C07F21", area: "C" },
  { id: "C07F22", unitNumber: "C07F22", area: "C" },
  { id: "C07F23", unitNumber: "C07F23", area: "C" },
  { id: "C08F03", unitNumber: "C08F03", area: "C" },
  { id: "C08F04", unitNumber: "C08F04", area: "C" },
  { id: "C08F05", unitNumber: "C08F05", area: "C" },
  { id: "C08F06", unitNumber: "C08F06", area: "C" },
  { id: "C08F07", unitNumber: "C08F07", area: "C" },
  { id: "C08F08", unitNumber: "C08F08", area: "C" },
  { id: "C08F09", unitNumber: "C08F09", area: "C" },
  { id: "C08F10", unitNumber: "C08F10", area: "C" },
  { id: "C08F11", unitNumber: "C08F11", area: "C" },
  { id: "C08F12", unitNumber: "C08F12", area: "C" },
  { id: "C08F13", unitNumber: "C08F13", area: "C" },
  { id: "C08F14", unitNumber: "C08F14", area: "C" },
  { id: "C08F15", unitNumber: "C08F15", area: "C" },
  { id: "C08F16", unitNumber: "C08F16", area: "C" },
  { id: "C08F17", unitNumber: "C08F17", area: "C" },
  { id: "C08F18", unitNumber: "C08F18", area: "C" },
  { id: "C08F19", unitNumber: "C08F19", area: "C" },
  { id: "C08F20", unitNumber: "C08F20", area: "C" },
  { id: "C08F21", unitNumber: "C08F21", area: "C" },
  { id: "C08F22", unitNumber: "C08F22", area: "C" },
  { id: "C08F23", unitNumber: "C08F23", area: "C" },
  { id: "C09F03", unitNumber: "C09F03", area: "C" },
  { id: "C09F04", unitNumber: "C09F04", area: "C" },
  { id: "C09F05", unitNumber: "C09F05", area: "C" },
  { id: "C09F06", unitNumber: "C09F06", area: "C" },
  { id: "C09F07", unitNumber: "C09F07", area: "C" },
  { id: "C09F08", unitNumber: "C09F08", area: "C" },
  { id: "C09F09", unitNumber: "C09F09", area: "C" },
  { id: "C09F10", unitNumber: "C09F10", area: "C" },
  { id: "C09F11", unitNumber: "C09F11", area: "C" },
  { id: "C09F12", unitNumber: "C09F12", area: "C" },
  { id: "C09F13", unitNumber: "C09F13", area: "C" },
  { id: "C09F14", unitNumber: "C09F14", area: "C" },
  { id: "C09F15", unitNumber: "C09F15", area: "C" },
  { id: "C09F16", unitNumber: "C09F16", area: "C" },
  { id: "C09F17", unitNumber: "C09F17", area: "C" },
  { id: "C09F18", unitNumber: "C09F18", area: "C" },
  { id: "C09F19", unitNumber: "C09F19", area: "C" },
  { id: "C09F20", unitNumber: "C09F20", area: "C" },
  { id: "C09F21", unitNumber: "C09F21", area: "C" },
  { id: "C09F22", unitNumber: "C09F22", area: "C" },
  { id: "C09F23", unitNumber: "C09F23", area: "C" },
];

export const initialParkingSpaces: ParkingSpace[] = [
  { number: "1", size: "大", allocation: "重", isAvailable: true },
  { number: "2", size: "大", allocation: "重", isAvailable: true },
  { number: "3", size: "大", allocation: "重", isAvailable: true },
  { number: "4", size: "大", allocation: "重", isAvailable: true },
  { number: "5", size: "大", allocation: "A", isAvailable: true },
  { number: "6", size: "大", allocation: "A", isAvailable: true },
  { number: "7", size: "大", allocation: "A", isAvailable: true },
  { number: "8", size: "大", allocation: "A", isAvailable: true },
  { number: "9", size: "小", allocation: "A", isAvailable: true },
  { number: "10", size: "小", allocation: "A", isAvailable: true },
  { number: "11", size: "小", allocation: "A", isAvailable: true },
  { number: "12", size: "小", allocation: "店", isAvailable: true },
  { number: "13", size: "小", allocation: "店", isAvailable: true },
  { number: "14", size: "小", allocation: "店", isAvailable: true },
  { number: "15", size: "小", allocation: "店", isAvailable: true },
  { number: "16", size: "小", allocation: "店", isAvailable: true },
  { number: "17A", size: "身障", allocation: "保留", isAvailable: false },
  { number: "17B", size: "身障", allocation: "保留", isAvailable: false },
  { number: "18A", size: "身障", allocation: "保留", isAvailable: false },
  { number: "18B", size: "身障", allocation: "保留", isAvailable: false },
  { number: "19", size: "小", allocation: "重", isAvailable: true },
  { number: "20", size: "小", allocation: "重", isAvailable: true },
  { number: "21", size: "大", allocation: "重", isAvailable: true },
  { number: "22", size: "大", allocation: "重", isAvailable: true },
  { number: "23A", size: "身障", allocation: "保留", isAvailable: false },
  { number: "23B", size: "身障", allocation: "保留", isAvailable: false },
  { number: "24A", size: "身障", allocation: "保留", isAvailable: false },
  { number: "24B", size: "身障", allocation: "保留", isAvailable: false },
  { number: "25A", size: "身障", allocation: "保留", isAvailable: false },
  { number: "25B", size: "身障", allocation: "保留", isAvailable: false },
  { number: "26A", size: "身障", allocation: "保留", isAvailable: false },
  { number: "26B", size: "身障", allocation: "保留", isAvailable: false },
  { number: "27", size: "小", allocation: "店", isAvailable: true },
  { number: "28", size: "身障", allocation: "保留", isAvailable: false },
  { number: "29", size: "身障", allocation: "保留", isAvailable: false },
  { number: "30", size: "身障", allocation: "保留", isAvailable: false },
  { number: "31", size: "身障", allocation: "保留", isAvailable: false },
  { number: "32", size: "大", allocation: "A", isAvailable: true },
  { number: "33", size: "大", allocation: "A", isAvailable: true },
  { number: "34", size: "大", allocation: "A", isAvailable: true },
  { number: "35", size: "大", allocation: "A", isAvailable: true },
  { number: "36", size: "大", allocation: "A", isAvailable: true },
  { number: "37", size: "大", allocation: "A", isAvailable: true },
  { number: "38", size: "大", allocation: "A", isAvailable: true },
  { number: "39", size: "大", allocation: "A", isAvailable: true },
  { number: "40", size: "大", allocation: "A", isAvailable: true },
  { number: "41", size: "大", allocation: "A", isAvailable: true },
  { number: "42", size: "大", allocation: "A", isAvailable: true },
  { number: "43", size: "大", allocation: "A", isAvailable: true },
  { number: "44", size: "大", allocation: "A", isAvailable: true },
  { number: "45", size: "大", allocation: "A", isAvailable: true },
  { number: "46", size: "大", allocation: "A", isAvailable: true },
  { number: "47", size: "大", allocation: "A", isAvailable: true },
  { number: "48", size: "大", allocation: "A", isAvailable: true },
  { number: "49", size: "大", allocation: "B", isAvailable: true },
  { number: "50", size: "大", allocation: "B", isAvailable: true },
  { number: "51", size: "大", allocation: "B", isAvailable: true },
  { number: "52", size: "大", allocation: "B", isAvailable: true },
  { number: "53", size: "大", allocation: "B", isAvailable: true },
  { number: "54", size: "大", allocation: "B", isAvailable: true },
  { number: "55", size: "大", allocation: "B", isAvailable: true },
  { number: "56", size: "大", allocation: "B", isAvailable: true },
  { number: "57", size: "大", allocation: "B", isAvailable: true },
  { number: "58", size: "大", allocation: "B", isAvailable: true },
  { number: "59", size: "大", allocation: "B", isAvailable: true },
  { number: "60", size: "大", allocation: "B", isAvailable: true },
  { number: "61", size: "大", allocation: "B", isAvailable: true },
  { number: "62", size: "大", allocation: "B", isAvailable: true },
  { number: "63", size: "大", allocation: "B", isAvailable: true },
  { number: "64", size: "大", allocation: "B", isAvailable: true },
  { number: "65", size: "大", allocation: "B", isAvailable: true },
  { number: "66", size: "大", allocation: "B", isAvailable: true },
  { number: "67", size: "大", allocation: "B", isAvailable: true },
  { number: "68", size: "大", allocation: "C", isAvailable: true },
  { number: "69", size: "大", allocation: "C", isAvailable: true },
  { number: "70", size: "大", allocation: "C", isAvailable: true },
  { number: "71", size: "大", allocation: "C", isAvailable: true },
  { number: "72", size: "大", allocation: "C", isAvailable: true },
  { number: "73", size: "大", allocation: "C", isAvailable: true },
  { number: "74", size: "大", allocation: "C", isAvailable: true },
  { number: "75", size: "大", allocation: "C", isAvailable: true },
  { number: "76", size: "大", allocation: "C", isAvailable: true },
  { number: "77", size: "大", allocation: "C", isAvailable: true },
  { number: "78", size: "大", allocation: "C", isAvailable: true },
  { number: "79", size: "大", allocation: "C", isAvailable: true },
  { number: "80", size: "大", allocation: "C", isAvailable: true },
  { number: "81", size: "大", allocation: "C", isAvailable: true },
  { number: "82", size: "大", allocation: "C", isAvailable: true },
  { number: "83", size: "大", allocation: "C", isAvailable: true },
  { number: "84", size: "大", allocation: "C", isAvailable: true },
  { number: "85", size: "大", allocation: "C", isAvailable: true },
  { number: "86", size: "大", allocation: "C", isAvailable: true },
  { number: "87", size: "大", allocation: "C", isAvailable: true },
  { number: "88", size: "大", allocation: "C", isAvailable: true },
  { number: "89", size: "大", allocation: "C", isAvailable: true },
  { number: "90", size: "大", allocation: "C", isAvailable: true },
  { number: "91", size: "大", allocation: "C", isAvailable: true },
  { number: "92", size: "小", allocation: "C", isAvailable: true },
  { number: "93", size: "小", allocation: "C", isAvailable: true },
  { number: "94", size: "大", allocation: "C", isAvailable: true },
  { number: "95", size: "大", allocation: "C", isAvailable: true },
  { number: "96", size: "大", allocation: "C", isAvailable: true },
  { number: "97", size: "小", allocation: "C", isAvailable: true },
  { number: "98", size: "小", allocation: "C", isAvailable: true },
  { number: "99", size: "小", allocation: "C", isAvailable: true },
  { number: "100", size: "小", allocation: "C", isAvailable: true },
  { number: "101", size: "大", allocation: "C", isAvailable: true },
  { number: "102", size: "大", allocation: "C", isAvailable: true },
  { number: "103", size: "大", allocation: "B", isAvailable: true },
  { number: "104", size: "小", allocation: "B", isAvailable: true },
  { number: "105", size: "大", allocation: "B", isAvailable: true },
  { number: "106", size: "大", allocation: "B", isAvailable: true },
  { number: "107", size: "大", allocation: "B", isAvailable: true },
  { number: "108", size: "大", allocation: "B", isAvailable: true },
  { number: "109", size: "大", allocation: "B", isAvailable: true },
  { number: "110", size: "大", allocation: "B", isAvailable: true },
  { number: "111", size: "大", allocation: "B", isAvailable: true },
  { number: "112", size: "大", allocation: "B", isAvailable: true },
  { number: "113", size: "大", allocation: "B", isAvailable: true },
  { number: "114", size: "大", allocation: "B", isAvailable: true },
  { number: "115", size: "大", allocation: "B", isAvailable: true },
  { number: "116", size: "大", allocation: "B", isAvailable: true },
  { number: "117", size: "大", allocation: "B", isAvailable: true },
  { number: "118", size: "大", allocation: "A", isAvailable: true },
  { number: "119", size: "大", allocation: "A", isAvailable: true },
  { number: "120", size: "大", allocation: "A", isAvailable: true },
  { number: "121", size: "大", allocation: "A", isAvailable: true },
  { number: "122", size: "大", allocation: "A", isAvailable: true },
  { number: "123", size: "大", allocation: "A", isAvailable: true },
  { number: "124", size: "大", allocation: "A", isAvailable: true },
  { number: "125", size: "大", allocation: "A", isAvailable: true },
  { number: "126", size: "小", allocation: "A", isAvailable: true },
  { number: "127", size: "小", allocation: "A", isAvailable: true },
  { number: "128", size: "小", allocation: "A", isAvailable: true },
  { number: "129", size: "小", allocation: "A", isAvailable: true },
  { number: "130", size: "小", allocation: "A", isAvailable: true },
  { number: "131", size: "大", allocation: "A", isAvailable: true },
  { number: "132", size: "大", allocation: "A", isAvailable: true },
  { number: "133", size: "大", allocation: "A", isAvailable: true },
  { number: "134", size: "大", allocation: "A", isAvailable: true },
  { number: "135", size: "大", allocation: "A", isAvailable: true },
  { number: "136", size: "大", allocation: "A", isAvailable: true },
  { number: "137", size: "大", allocation: "A", isAvailable: true },
  { number: "138", size: "大", allocation: "A", isAvailable: true },
  { number: "139", size: "大", allocation: "A", isAvailable: true },
  { number: "140", size: "大", allocation: "A", isAvailable: true },
  { number: "141", size: "大", allocation: "A", isAvailable: true },
  { number: "142", size: "大", allocation: "A", isAvailable: true },
  { number: "143", size: "大", allocation: "A", isAvailable: true },
  { number: "144", size: "大", allocation: "A", isAvailable: true },
  { number: "145", size: "大", allocation: "A", isAvailable: true },
  { number: "146", size: "大", allocation: "A", isAvailable: true },
  { number: "147", size: "大", allocation: "A", isAvailable: true },
  { number: "148", size: "大", allocation: "A", isAvailable: true },
  { number: "149", size: "大", allocation: "A", isAvailable: true },
  { number: "150", size: "大", allocation: "A", isAvailable: true },
  { number: "151", size: "大", allocation: "A", isAvailable: true },
  { number: "152", size: "大", allocation: "A", isAvailable: true },
  { number: "153", size: "大", allocation: "A", isAvailable: true },
  { number: "154", size: "大", allocation: "A", isAvailable: true },
  { number: "155", size: "大", allocation: "A", isAvailable: true },
  { number: "156", size: "大", allocation: "A", isAvailable: true },
  { number: "157", size: "大", allocation: "A", isAvailable: true },
  { number: "158", size: "大", allocation: "A", isAvailable: true },
  { number: "159", size: "小", allocation: "A", isAvailable: true },
  { number: "160", size: "大", allocation: "A", isAvailable: true },
  { number: "161", size: "大", allocation: "A", isAvailable: true },
  { number: "162", size: "大", allocation: "A", isAvailable: true },
  { number: "163", size: "大", allocation: "A", isAvailable: true },
  { number: "164", size: "大", allocation: "A", isAvailable: true },
  { number: "165", size: "大", allocation: "A", isAvailable: true },
  { number: "166", size: "大", allocation: "A", isAvailable: true },
  { number: "167", size: "大", allocation: "A", isAvailable: true },
  { number: "168", size: "小", allocation: "B", isAvailable: true },
  { number: "169", size: "大", allocation: "B", isAvailable: true },
  { number: "170", size: "大", allocation: "B", isAvailable: true },
  { number: "171", size: "大", allocation: "B", isAvailable: true },
  { number: "172", size: "大", allocation: "B", isAvailable: true },
  { number: "173", size: "大", allocation: "B", isAvailable: true },
  { number: "174", size: "大", allocation: "B", isAvailable: true },
  { number: "175", size: "大", allocation: "B", isAvailable: true },
  { number: "176", size: "大", allocation: "B", isAvailable: true },
  { number: "177", size: "大", allocation: "B", isAvailable: true },
  { number: "178", size: "大", allocation: "B", isAvailable: true },
  { number: "179", size: "大", allocation: "B", isAvailable: true },
  { number: "180", size: "大", allocation: "B", isAvailable: true },
  { number: "181", size: "大", allocation: "B", isAvailable: true },
  { number: "182", size: "大", allocation: "B", isAvailable: true },
  { number: "183", size: "大", allocation: "B", isAvailable: true },
  { number: "184", size: "大", allocation: "B", isAvailable: true },
  { number: "185", size: "大", allocation: "B", isAvailable: true },
  { number: "186", size: "大", allocation: "B", isAvailable: true },
  { number: "187", size: "大", allocation: "B", isAvailable: true },
  { number: "188", size: "大", allocation: "B", isAvailable: true },
  { number: "189", size: "大", allocation: "B", isAvailable: true },
  { number: "190", size: "大", allocation: "B", isAvailable: true },
  { number: "191", size: "大", allocation: "B", isAvailable: true },
  { number: "192", size: "大", allocation: "B", isAvailable: true },
  { number: "193", size: "大", allocation: "B", isAvailable: true },
  { number: "194", size: "大", allocation: "B", isAvailable: true },
  { number: "195", size: "大", allocation: "B", isAvailable: true },
  { number: "196", size: "大", allocation: "B", isAvailable: true },
  { number: "197", size: "大", allocation: "B", isAvailable: true },
  { number: "198", size: "大", allocation: "B", isAvailable: true },
  { number: "199", size: "大", allocation: "B", isAvailable: true },
  { number: "200", size: "大", allocation: "B", isAvailable: true },
  { number: "201", size: "大", allocation: "C", isAvailable: true },
  { number: "202", size: "大", allocation: "C", isAvailable: true },
  { number: "203", size: "大", allocation: "C", isAvailable: true },
  { number: "204", size: "大", allocation: "C", isAvailable: true },
  { number: "205", size: "大", allocation: "C", isAvailable: true },
  { number: "206", size: "大", allocation: "C", isAvailable: true },
  { number: "207", size: "大", allocation: "C", isAvailable: true },
  { number: "208", size: "大", allocation: "C", isAvailable: true },
  { number: "209", size: "大", allocation: "C", isAvailable: true },
  { number: "210", size: "大", allocation: "C", isAvailable: true },
  { number: "211", size: "大", allocation: "C", isAvailable: true },
  { number: "212", size: "大", allocation: "C", isAvailable: true },
  { number: "213", size: "大", allocation: "C", isAvailable: true },
  { number: "214", size: "大", allocation: "C", isAvailable: true },
  { number: "215", size: "大", allocation: "C", isAvailable: true },
  { number: "216", size: "大", allocation: "C", isAvailable: true },
  { number: "217", size: "大", allocation: "C", isAvailable: true },
  { number: "218", size: "大", allocation: "C", isAvailable: true },
  { number: "219", size: "大", allocation: "C", isAvailable: true },
  { number: "220", size: "大", allocation: "C", isAvailable: true },
  { number: "221", size: "大", allocation: "C", isAvailable: true },
  { number: "222", size: "大", allocation: "C", isAvailable: true },
  { number: "223", size: "大", allocation: "C", isAvailable: true },
  { number: "224", size: "大", allocation: "C", isAvailable: true },
  { number: "225", size: "小", allocation: "C", isAvailable: true },
  { number: "226", size: "小", allocation: "C", isAvailable: true },
  { number: "227", size: "小", allocation: "C", isAvailable: true },
  { number: "228", size: "小", allocation: "C", isAvailable: true },
  { number: "229", size: "大", allocation: "C", isAvailable: true },
  { number: "230", size: "大", allocation: "C", isAvailable: true },
  { number: "231", size: "大", allocation: "C", isAvailable: true },
  { number: "232", size: "大", allocation: "C", isAvailable: true },
  { number: "233", size: "大", allocation: "C", isAvailable: true },
  { number: "234", size: "大", allocation: "C", isAvailable: true },
  { number: "235", size: "小", allocation: "C", isAvailable: true },
  { number: "236", size: "小", allocation: "C", isAvailable: true },
  { number: "237", size: "小", allocation: "C", isAvailable: true },
  { number: "238", size: "小", allocation: "C", isAvailable: true },
  { number: "239", size: "小", allocation: "C", isAvailable: true },
  { number: "240", size: "小", allocation: "C", isAvailable: true },
  { number: "241", size: "小", allocation: "C", isAvailable: true },
  { number: "242", size: "小", allocation: "C", isAvailable: true },
  { number: "243", size: "小", allocation: "C", isAvailable: true },
  { number: "244", size: "小", allocation: "C", isAvailable: true },
  { number: "245", size: "小", allocation: "C", isAvailable: true },
  { number: "246", size: "小", allocation: "C", isAvailable: true },
  { number: "247", size: "小", allocation: "C", isAvailable: true },
  { number: "248", size: "小", allocation: "C", isAvailable: true },
  { number: "249", size: "小", allocation: "C", isAvailable: true },
  { number: "250", size: "小", allocation: "C", isAvailable: true },
  { number: "251", size: "小", allocation: "C", isAvailable: true },
  { number: "252", size: "大", allocation: "C", isAvailable: true },
  { number: "253", size: "大", allocation: "C", isAvailable: true },
  { number: "254", size: "大", allocation: "C", isAvailable: true },
  { number: "255", size: "大", allocation: "C", isAvailable: true },
  { number: "256", size: "大", allocation: "C", isAvailable: true },
  { number: "257", size: "大", allocation: "C", isAvailable: true },
  { number: "258", size: "大", allocation: "C", isAvailable: true },
  { number: "259", size: "小", allocation: "C", isAvailable: true },
  { number: "260", size: "小", allocation: "C", isAvailable: true },
  { number: "261", size: "小", allocation: "C", isAvailable: true },
  { number: "262", size: "大", allocation: "C", isAvailable: true },
  { number: "263", size: "大", allocation: "C", isAvailable: true },
  { number: "264", size: "大", allocation: "C", isAvailable: true },
  { number: "265", size: "大", allocation: "C", isAvailable: true },
  { number: "266", size: "大", allocation: "C", isAvailable: true },
  { number: "267", size: "大", allocation: "C", isAvailable: true },
  { number: "268", size: "大", allocation: "C", isAvailable: true },
  { number: "269", size: "大", allocation: "C", isAvailable: true },
  { number: "270", size: "大", allocation: "C", isAvailable: true },
  { number: "271", size: "大", allocation: "C", isAvailable: true },
  { number: "272", size: "大", allocation: "C", isAvailable: true },
  { number: "273", size: "大", allocation: "C", isAvailable: true },
  { number: "274", size: "大", allocation: "C", isAvailable: true },
  { number: "275", size: "大", allocation: "C", isAvailable: true },
  { number: "276", size: "大", allocation: "C", isAvailable: true },
  { number: "277", size: "大", allocation: "B", isAvailable: true },
  { number: "278", size: "大", allocation: "B", isAvailable: true },
  { number: "279", size: "小", allocation: "B", isAvailable: true },
  { number: "280", size: "小", allocation: "B", isAvailable: true },
  { number: "281", size: "小", allocation: "B", isAvailable: true },
  { number: "282", size: "大", allocation: "B", isAvailable: true },
  { number: "283", size: "大", allocation: "B", isAvailable: true },
  { number: "284", size: "大", allocation: "B", isAvailable: true },
  { number: "285", size: "大", allocation: "B", isAvailable: true },
  { number: "286", size: "小", allocation: "B", isAvailable: true },
  { number: "287", size: "大", allocation: "B", isAvailable: true },
  { number: "288", size: "大", allocation: "B", isAvailable: true },
  { number: "289", size: "大", allocation: "B", isAvailable: true },
  { number: "290", size: "大", allocation: "B", isAvailable: true },
  { number: "291", size: "大", allocation: "B", isAvailable: true },
  { number: "292", size: "大", allocation: "B", isAvailable: true },
  { number: "293", size: "小", allocation: "B", isAvailable: true },
  { number: "294", size: "小", allocation: "B", isAvailable: true },
  { number: "295", size: "大", allocation: "B", isAvailable: true },
  { number: "296", size: "大", allocation: "B", isAvailable: true },
  { number: "297", size: "大", allocation: "A", isAvailable: true },
  { number: "298", size: "大", allocation: "A", isAvailable: true },
  { number: "299", size: "大", allocation: "A", isAvailable: true },
  { number: "300", size: "大", allocation: "A", isAvailable: true },
  { number: "301", size: "小", allocation: "A", isAvailable: true },
  { number: "302", size: "小", allocation: "A", isAvailable: true },
  { number: "303", size: "大", allocation: "A", isAvailable: true },
  { number: "304", size: "大", allocation: "A", isAvailable: true },
  { number: "305", size: "大", allocation: "A", isAvailable: true },
  { number: "306", size: "小", allocation: "A", isAvailable: true },
  { number: "307", size: "小", allocation: "A", isAvailable: true },
  { number: "308", size: "小", allocation: "A", isAvailable: true },
  { number: "309", size: "小", allocation: "A", isAvailable: true },
  { number: "310", size: "小", allocation: "A", isAvailable: true },
  { number: "311", size: "小", allocation: "A", isAvailable: true },
  { number: "312", size: "小", allocation: "A", isAvailable: true },
  { number: "313", size: "小", allocation: "A", isAvailable: true },
  { number: "314", size: "小", allocation: "A", isAvailable: true },
  { number: "315", size: "小", allocation: "A", isAvailable: true },
  { number: "316", size: "小", allocation: "A", isAvailable: true },
  { number: "317", size: "小", allocation: "A", isAvailable: true },
  { number: "318", size: "小", allocation: "A", isAvailable: true },
  { number: "319", size: "小", allocation: "A", isAvailable: true },
  { number: "320", size: "小", allocation: "A", isAvailable: true },
  { number: "321", size: "小", allocation: "A", isAvailable: true },
  { number: "322", size: "小", allocation: "A", isAvailable: true },
  { number: "323", size: "小", allocation: "A", isAvailable: true },
  { number: "324", size: "小", allocation: "A", isAvailable: true },
  { number: "325", size: "小", allocation: "A", isAvailable: true },
  { number: "326", size: "小", allocation: "A", isAvailable: true },
  { number: "327", size: "小", allocation: "A", isAvailable: true },
  { number: "328", size: "小", allocation: "A", isAvailable: true },
  { number: "329", size: "小", allocation: "A", isAvailable: true },
  { number: "330", size: "小", allocation: "A", isAvailable: true },
  { number: "331", size: "小", allocation: "A", isAvailable: true },
  { number: "332", size: "小", allocation: "店", isAvailable: true },
  { number: "333", size: "小", allocation: "店", isAvailable: true },
  { number: "334", size: "小", allocation: "店", isAvailable: true },
  { number: "335", size: "小", allocation: "店", isAvailable: true },
  { number: "336", size: "小", allocation: "店", isAvailable: true },
  { number: "337", size: "小", allocation: "店", isAvailable: true },
  { number: "338", size: "小", allocation: "店", isAvailable: true },
  { number: "339", size: "小", allocation: "店", isAvailable: true },
  { number: "340", size: "小", allocation: "店", isAvailable: true },
  { number: "341", size: "小", allocation: "店", isAvailable: true },
  { number: "342", size: "小", allocation: "店", isAvailable: true },
  { number: "343", size: "小", allocation: "店", isAvailable: true },
  { number: "344", size: "小", allocation: "店", isAvailable: true },
  { number: "345", size: "小", allocation: "店", isAvailable: true },
  { number: "346", size: "小", allocation: "A", isAvailable: true },
  { number: "347", size: "小", allocation: "A", isAvailable: true },
  { number: "348", size: "小", allocation: "A", isAvailable: true },
  { number: "349", size: "小", allocation: "A", isAvailable: true },
  { number: "350", size: "小", allocation: "A", isAvailable: true },
  { number: "351", size: "小", allocation: "A", isAvailable: true },
  { number: "352", size: "小", allocation: "A", isAvailable: true },
  { number: "353", size: "小", allocation: "A", isAvailable: true },
  { number: "354", size: "小", allocation: "A", isAvailable: true },
  { number: "355", size: "小", allocation: "A", isAvailable: true },
  { number: "356", size: "小", allocation: "A", isAvailable: true },
  { number: "357", size: "小", allocation: "A", isAvailable: true },
  { number: "358", size: "小", allocation: "A", isAvailable: true },
  { number: "359", size: "小", allocation: "A", isAvailable: true },
  { number: "360", size: "小", allocation: "A", isAvailable: true },
  { number: "361", size: "小", allocation: "A", isAvailable: true },
  { number: "362", size: "小", allocation: "B", isAvailable: true },
  { number: "363", size: "小", allocation: "B", isAvailable: true },
  { number: "364", size: "小", allocation: "B", isAvailable: true },
  { number: "365", size: "小", allocation: "B", isAvailable: true },
  { number: "366", size: "小", allocation: "B", isAvailable: true },
  { number: "367", size: "小", allocation: "B", isAvailable: true },
  { number: "368", size: "小", allocation: "B", isAvailable: true },
  { number: "369", size: "小", allocation: "B", isAvailable: true },
  { number: "370", size: "小", allocation: "B", isAvailable: true },
  { number: "371", size: "小", allocation: "B", isAvailable: true },
  { number: "372", size: "小", allocation: "B", isAvailable: true },
  { number: "373", size: "小", allocation: "B", isAvailable: true },
  { number: "374", size: "小", allocation: "B", isAvailable: true },
  { number: "375", size: "小", allocation: "B", isAvailable: true },
  { number: "376", size: "小", allocation: "B", isAvailable: true },
  { number: "377", size: "小", allocation: "B", isAvailable: true },
  { number: "378", size: "小", allocation: "B", isAvailable: true },
  { number: "379", size: "小", allocation: "B", isAvailable: true },
  { number: "380", size: "小", allocation: "B", isAvailable: true },
  { number: "381", size: "小", allocation: "B", isAvailable: true },
  { number: "382", size: "小", allocation: "B", isAvailable: true },
  { number: "383", size: "小", allocation: "B", isAvailable: true },
  { number: "384", size: "小", allocation: "B", isAvailable: true },
  { number: "385", size: "小", allocation: "B", isAvailable: true },
  { number: "386", size: "小", allocation: "B", isAvailable: true },
  { number: "387", size: "小", allocation: "B", isAvailable: true },
  { number: "388", size: "小", allocation: "B", isAvailable: true },
  { number: "389", size: "小", allocation: "B", isAvailable: true },
  { number: "390", size: "小", allocation: "B", isAvailable: true },
  { number: "391", size: "小", allocation: "B", isAvailable: true },
  { number: "392", size: "小", allocation: "B", isAvailable: true },
  { number: "393", size: "小", allocation: "B", isAvailable: true },
  { number: "394", size: "小", allocation: "B", isAvailable: true },
  { number: "395", size: "小", allocation: "B", isAvailable: true },
  { number: "396", size: "小", allocation: "C", isAvailable: true },
  { number: "397", size: "小", allocation: "C", isAvailable: true },
  { number: "398", size: "小", allocation: "C", isAvailable: true },
  { number: "399", size: "小", allocation: "C", isAvailable: true },
  { number: "400", size: "小", allocation: "C", isAvailable: true },
  { number: "401", size: "小", allocation: "C", isAvailable: true },
  { number: "402", size: "小", allocation: "C", isAvailable: true },
  { number: "403", size: "小", allocation: "C", isAvailable: true },
  { number: "404", size: "小", allocation: "C", isAvailable: true },
  { number: "405", size: "小", allocation: "C", isAvailable: true },
  { number: "406", size: "小", allocation: "C", isAvailable: true },
  { number: "407", size: "小", allocation: "C", isAvailable: true },
  { number: "408", size: "小", allocation: "C", isAvailable: true },
  { number: "409", size: "小", allocation: "C", isAvailable: true },
  { number: "410", size: "小", allocation: "C", isAvailable: true },
  { number: "411", size: "小", allocation: "C", isAvailable: true },
  { number: "412", size: "小", allocation: "C", isAvailable: true },
  { number: "413", size: "小", allocation: "C", isAvailable: true },
  { number: "414", size: "小", allocation: "C", isAvailable: true },
  { number: "415", size: "小", allocation: "C", isAvailable: true },
  { number: "416", size: "小", allocation: "C", isAvailable: true },
  { number: "417", size: "小", allocation: "C", isAvailable: true },
  { number: "418", size: "小", allocation: "C", isAvailable: true },
  { number: "419", size: "小", allocation: "C", isAvailable: true },
  { number: "420", size: "小", allocation: "C", isAvailable: true },
  { number: "421", size: "小", allocation: "C", isAvailable: true },
  { number: "422", size: "小", allocation: "C", isAvailable: true },
  { number: "423", size: "小", allocation: "C", isAvailable: true },
  { number: "424", size: "小", allocation: "C", isAvailable: true },
  { number: "425", size: "小", allocation: "C", isAvailable: true },
  { number: "426", size: "小", allocation: "C", isAvailable: true },
  { number: "427", size: "小", allocation: "C", isAvailable: true },
  { number: "428", size: "小", allocation: "C", isAvailable: true },
  { number: "429", size: "小", allocation: "C", isAvailable: true },
  { number: "430", size: "小", allocation: "C", isAvailable: true },
  { number: "431", size: "小", allocation: "C", isAvailable: true },
  { number: "432", size: "小", allocation: "C", isAvailable: true },
  { number: "433", size: "小", allocation: "C", isAvailable: true },
  { number: "434", size: "小", allocation: "C", isAvailable: true },
  { number: "435", size: "小", allocation: "C", isAvailable: true },
  { number: "436", size: "小", allocation: "C", isAvailable: true },
  { number: "437", size: "小", allocation: "C", isAvailable: true },
  { number: "438", size: "小", allocation: "C", isAvailable: true },
  { number: "439", size: "小", allocation: "C", isAvailable: true },
  { number: "440", size: "小", allocation: "C", isAvailable: true },
  { number: "441", size: "小", allocation: "C", isAvailable: true },
  { number: "442", size: "小", allocation: "C", isAvailable: true },
  { number: "443", size: "小", allocation: "C", isAvailable: true },
  { number: "444", size: "小", allocation: "C", isAvailable: true },
  { number: "445", size: "小", allocation: "B", isAvailable: true },
  { number: "446", size: "小", allocation: "B", isAvailable: true },
  { number: "447", size: "小", allocation: "B", isAvailable: true },
  { number: "448", size: "小", allocation: "B", isAvailable: true },
  { number: "449", size: "小", allocation: "B", isAvailable: true },
  { number: "450", size: "小", allocation: "B", isAvailable: true },
  { number: "451", size: "小", allocation: "B", isAvailable: true },
  { number: "452", size: "小", allocation: "B", isAvailable: true },
  { number: "453", size: "小", allocation: "B", isAvailable: true },
  { number: "454", size: "小", allocation: "B", isAvailable: true },
  { number: "455", size: "小", allocation: "B", isAvailable: true },
  { number: "456", size: "小", allocation: "B", isAvailable: true },
  { number: "457", size: "小", allocation: "B", isAvailable: true },
  { number: "458", size: "小", allocation: "B", isAvailable: true },
  { number: "459", size: "小", allocation: "B", isAvailable: true },
  { number: "460", size: "小", allocation: "B", isAvailable: true },
  { number: "461", size: "小", allocation: "B", isAvailable: true },
  { number: "462", size: "小", allocation: "B", isAvailable: true },
  { number: "463", size: "小", allocation: "B", isAvailable: true },
  { number: "464", size: "小", allocation: "B", isAvailable: true },
  { number: "465", size: "小", allocation: "B", isAvailable: true },
  { number: "466", size: "小", allocation: "B", isAvailable: true },
  { number: "467", size: "小", allocation: "B", isAvailable: true },
  { number: "468", size: "小", allocation: "B", isAvailable: true },
  { number: "469", size: "小", allocation: "B", isAvailable: true },
  { number: "470", size: "小", allocation: "B", isAvailable: true },
  { number: "471", size: "小", allocation: "B", isAvailable: true },
  { number: "472", size: "小", allocation: "B", isAvailable: true },
  { number: "473", size: "小", allocation: "B", isAvailable: true },
  { number: "474", size: "小", allocation: "B", isAvailable: true },
  { number: "475", size: "小", allocation: "B", isAvailable: true },
  { number: "476", size: "小", allocation: "B", isAvailable: true },
  { number: "477", size: "小", allocation: "B", isAvailable: true },
  { number: "478", size: "小", allocation: "B", isAvailable: true },
  { number: "479", size: "小", allocation: "A", isAvailable: true },
  { number: "480", size: "小", allocation: "A", isAvailable: true },
  { number: "481", size: "小", allocation: "A", isAvailable: true },
  { number: "482", size: "小", allocation: "A", isAvailable: true },
  { number: "483", size: "小", allocation: "A", isAvailable: true },
  { number: "484", size: "小", allocation: "A", isAvailable: true },
  { number: "485", size: "小", allocation: "A", isAvailable: true },
  { number: "486", size: "小", allocation: "A", isAvailable: true },
  { number: "487", size: "小", allocation: "A", isAvailable: true },
  { number: "488", size: "小", allocation: "A", isAvailable: true },
  { number: "489", size: "小", allocation: "A", isAvailable: true },
  { number: "490", size: "小", allocation: "A", isAvailable: true },
  { number: "491", size: "小", allocation: "A", isAvailable: true },
  { number: "492", size: "小", allocation: "A", isAvailable: true },
  { number: "493", size: "小", allocation: "A", isAvailable: true },
  { number: "494", size: "小", allocation: "A", isAvailable: true },
];
